conda run -n "advir" --no-capture-output \
  python adv_train.py \
  --de_type denoise_15 denoise_25 denoise_50 derain dehaze \
  --epochs "128" \
  --batch_size "4" \
  --accumulate_grad_batches "2" \
  --lr "2e-4" \
  --patch_size "128" \
  --num_workers "8" \
  --num_gpus "2" \
  --ckpt_dir "/home/huhao/adv_ir/exp/train_ckpt_adv50" \
  --adv_ratio "0.2" \
  --adv_resample_epochs "4" \
  --adv_steps1 "3" \
  --adv_steps2 "4" \
  --adv_step_size "0.03" \
  --adv_lambda_reg "0.05" \
  --adv_rain_topk "8" \
  --adv_promptir_patch_size "128" \
  --adv_promptir_patch_overlap "32" \
  --adv_cache_root "/home/huhao/adv_ir/PromptIR/data/Train/adv_pairs" \
  --adv_attack_device "cuda" \
  --auto_resume